import '@/styles/globals.css'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import DefaultLayout from '@/layouts/DefaultLayout'
import WithoutHeader from '@/layouts/WithoutHeader'
import WithTransparentHeader from '@/layouts/WithTransparentHeader'

const inter = Inter({ subsets: ['latin'] })

const layouts = {
  default: DefaultLayout,
  no_header: WithoutHeader,
  transparent_header: WithTransparentHeader,
}

const MetaHead = () => (
  <Head>
    <title>Future Living</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
)

export default function App({ Component, pageProps }) {
  if (Component.layout) {
    const Layout = layouts[Component.layout] || ((children) => <>{children}</>)
    return (
      <>
        <MetaHead />
        <Layout>
          <main className={`${inter.className} text-zinc-800 min-h-screen bg-white`}>
            <Component {...pageProps} />
          </main>
        </Layout>
      </>
    )
  }

  return (
    <>
      <MetaHead />
      <main className={`${inter.className} text-zinc-800 min-h-screen bg-white`}>
        <Component {...pageProps} />
      </main>
    </>
  )
}
